defaults:
  - _self_

batch_size: 64
seed: 43
debugrun: false
wandb_cfg:
  project: ikarus_bimanual
  run_name: ${now:%Y%m%d-%H%M%S}_${.project}
  tags: ["ikarus", "bimanual", "act"]
  mode: "online"
output_dir: runs/${wandb_cfg.run_name}

pipeline:
  _target_: srl_il.pipeline.imitation_learning.ImitationLearningPipeline

dataset_cfg:
  data:
    _target_: srl_il.dataset.faive_dataset.faive_train_val_test
    data_directory: Data/ikarus_bimanual_h5
    test_fraction: 0.1
    val_fraction: 0.1
    window_size_train: 20
    window_size_test: 20
    keys_traj: [
      ['actions_ikarus_arm', 'actions_ikarus_arm', 0, null],
      ['actions_ikarus_hand', 'actions_ikarus_hand', 0, null],
      ['qpos_ikarus_arm', 'qpos_ikarus_arm', 0, 1],
      ['qpos_ikarus_hand', 'qpos_ikarus_hand', 0, 1],
      ['head_images', 'head/color', 0, 1],
    ]
    keys_global: []
    pad_before: false
    pad_after: true
    pad_type: 'near'
    random_seed: ${seed}
  batch_size: ${batch_size}
  pin_memory: true
  num_workers: 2

algo_cfg:
  _target_: srl_il.algo.act.ACTPolicyTrainer
  algo_cfg:
    device: cuda
    target_dims:
      actions_ikarus_arm: 12
      actions_ikarus_hand: 32
    z_dim: 32
    T_target: 20
    T_z: 1
    encoder_is_causal: false
    decoder_is_causal: true
    encoder_group_keys: ['qpos']
    decoder_group_keys: ['qpos', 'head_images']
    encoder_cfg:
      d_model: 256
      nhead: 8
      num_encoder_layers: 3
      dim_feedforward: 1024
      dropout: 0.1
      activation: 'relu'
    decoder_cfg:
      d_model: 256
      nhead: 8
      num_encoder_layers: 3
      dim_feedforward: 1024
      dropout: 0.1
      activation: 'relu'
  trainer_cfg:
    loss_params:
      kl_weight: 10
    optimizer_cfg:
      act_encoder:
        optm_cls: torch.optim.Adam
        lr: 0.0001
      act_decoder:
        optm_cls: torch.optim.Adam
        lr: 0.0001
      obs_encoder:
        optm_cls: torch.optim.Adam
        lr: 0.0001
      projs:
        optm_cls: torch.optim.Adam
        lr: 0.0001
      embeds:
        optm_cls: torch.optim.Adam
        lr: 0.0001
  obs_encoder_cfg:
    output_dim: 256
    obs_groups_cfg:
      qpos:
        datakeys: ['qpos_ikarus_arm', 'qpos_ikarus_hand']
        encoder_cfg:
          type: lowdim_concat
          input_dim_total: 44
        posemb_cfg:
          type: none
      head_images:
        datakeys: ['head_images']
        encoder_cfg:
          type: crop_resnet18
          resize_shape: [224, 224]
          crop_shape: null
          pretrained: true
        posemb_cfg:
          type: none
    group_emb_cfg:
      type: "whole_seq_sine"

  policy_cfg:
    policy_bs: 1
    policy_translator: null
    policy_aggregator_cfg:
      type: "temporal_aggr"
      update_every: 1
      k: 0.01
    policy_obs_list:
      - ['qpos_ikarus_arm', 1]
      - ['qpos_ikarus_hand', 1]
      - ['head_images', 2]

lr_scheduler_cfg:
  act_encoder:
    type: "diffusers"
    name: cosine
    params:
      num_warmup_steps: 400
      num_training_steps: 800000
    step_with_metrics: false
  act_decoder:
    type: "diffusers"
    name: cosine
    params:
      num_warmup_steps: 400
      num_training_steps: 800000
    step_with_metrics: false
  obs_encoder:
    type: "diffusers"
    name: cosine
    params:
      num_warmup_steps: 2000
      num_training_steps: 800000
    step_with_metrics: false

training_cfg:
  num_epochs: 500
  num_steps_per_epoch: 100
  num_eval_steps_per_epoch: 10
  steps_saving: 10
  rollout:
    enabled: false
  visualization:
    enabled: true
    num_samples: 5
    every_n_epoch: 10

normalizer_cfg:
  actions_ikarus_arm:
    type: dataset_stats
    min_max: true
    dataname: actions_ikarus_arm
  actions_ikarus_hand:
    type: dataset_stats
    min_max: true
    dataname: actions_ikarus_hand
  qpos_ikarus_arm:
    type: dataset_stats
    dataname: qpos_ikarus_arm
  qpos_ikarus_hand:
    type: dataset_stats
    dataname: qpos_ikarus_hand
  head_images:
    type: hardcode
    mean: [[[0.485]], [[0.456]], [[0.406]]]
    std: [[[0.229]], [[0.224]], [[0.225]]]

data_augmentation_cfg:
  data_augments:
    - outname: qpos_ikarus_hand
      type: gaussian_noise
      mean: 0.0
      std: 0.01

sim_env_cfg: {}
projection_visualizer_cfg: {}

hydra:
  output_subdir: ${output_dir}/hydra
  run:
    dir: .
